### ISSUE TITLE
upload error but downloAD WORKING PROPERLY PLEASE HELP ME FIX .....HEROKU

### ISSUE THREAD

**Issue by AmirulAndalib** [azamaulanaaa/botkaca#40]
2021-02-14T16:14:26.156956+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-14T16:14:26.156964+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 204, in update_worker
2021-02-14T16:14:26.156964+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-02-14T16:14:26.156965+00:00 app[worker.1]:   File "/app/bot/handlers/leech_handler.py", line 67, in func
2021-02-14T16:14:26.156968+00:00 app[worker.1]:     await upload_files(client, reply, abs_files(download_dir, download.files), os_path_join(download_dir, download.name + '.zip'))
2021-02-14T16:14:26.156969+00:00 app[worker.1]:   File "/app/bot/handlers/leech_handler.py", line 89, in upload_files
2021-02-14T16:14:26.156969+00:00 app[worker.1]:     await upload_to_tg_handler.func(
2021-02-14T16:14:26.156969+00:00 app[worker.1]:   File "/app/bot/handlers/upload_to_tg_handler.py", line 107, in func
2021-02-14T16:14:26.156970+00:00 app[worker.1]:     await upload_fn(
2021-02-14T16:14:26.156971+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/client/methods/messages/send_document.py", line 141, in send_document
2021-02-14T16:14:26.156971+00:00 app[worker.1]:     if os.path.exists(document):
2021-02-14T16:14:26.156971+00:00 app[worker.1]:   File "/usr/lib/python3.8/genericpath.py", line 19, in exists
2021-02-14T16:14:26.156971+00:00 app[worker.1]:     os.stat(path)
2021-02-14T16:14:26.156972+00:00 app[worker.1]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.FileIO

**Comment by IshwaranRudhara** [comment]
**G_G**

**Comment by AmirulAndalib** [comment]
do something na Or Troubleshoot  pls

**Comment by IshwaranRudhara** [comment]
G_G

**Comment by devillD** [comment]
F

**Comment by IshwaranRudhara** [comment]
DUDE, TG me PLOX
