### ISSUE TITLE
TRACKER LIST UPDATE

### ISSUE THREAD

**Issue by talkaal** [azamaulanaaa/botkaca#5]
I have heard that updating tracker list increases speed of Torrent.

If in that case, I would like to suggest a feature.
**A Config variable to update trackers list**

I'm not sure if it's effective.
But just a thought.
If it's meaningful **please do add** or **close this issue.**

Thank you🙂

**Comment by azamaulanaaa** [comment]
please do testing to additional tracker feature. thank you.

**Comment by talkaal** [comment]
Surely I tested after updating the tracker list through  **config_variable**   in heroku.
Since In telegram the /set tracker list updates only to message line limit of telegram.


I'll add the Torrent link
Along with the error log

**TORRENT**
magnet:?xt=urn:btih:20A563CCBBD82F42A31BC83B542C90EAB7F1DD79&dn=undefined&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2920%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce




**ERROR_LOG**

2020-10-05T15:34:20.465431+00:00 app[worker.1]:     self.storage.auth_key(await Auth(self, self.storage.dc_id()).create())
2020-10-05T15:34:20.465432+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/auth.py", line 257, in create
2020-10-05T15:34:20.465432+00:00 app[worker.1]:     raise e
2020-10-05T15:34:20.465433+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/auth.py", line 83, in create
2020-10-05T15:34:20.465433+00:00 app[worker.1]:     await self.connection.connect()
2020-10-05T15:34:20.465434+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/connection/connection.py", line 70, in connect
2020-10-05T15:34:20.465434+00:00 app[worker.1]:     raise TimeoutError
2020-10-05T15:34:20.465435+00:00 app[worker.1]: TimeoutError
2020-10-05T15:34:59.990202+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=obscure-hollows-94063.herokuapp.com request_id=547a1e2a-49ef-4014-bcc1-ca3ef93d400b fwd="149.154.161.4" dyno= connect= service= status=503 bytes= protocol=https
2020-10-05T15:35:42.876118+00:00 app[worker.1]: 05-Oct-20 15:35:42 - bot.plugins.aria2 - INFO - ['aria2c', '--enable-rpc', '--dir=/app/downloads', '--daemon=true', '--max-connection-per-server=10', '--rpc-listen-all=false', '--rpc-listen-port=6800', '--seed-ratio=0', '--seed-time=0']
2020-10-05T15:35:42.887724+00:00 app[worker.1]: 05-Oct-20 15:35:42 - bot.plugins.aria2 - INFO - b''
2020-10-05T15:41:47.199894+00:00 app[worker.1]: 05-Oct-20 15:41:47 - root - INFO - NetWorkerTask started
2020-10-05T15:41:47.766051+00:00 app[worker.1]: 05-Oct-20 15:41:47 - bot.handlers.leech_handler - ERROR - [400 MESSAGE_NOT_MODIFIED]: The message was not modified (caused by "messages.EditMessage")
2020-10-05T15:41:47.766063+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-05T15:41:47.766064+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
2020-10-05T15:41:47.766066+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2020-10-05T15:41:47.766066+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 394, in _send
2020-10-05T15:41:47.766067+00:00 app[worker.1]:     raise TimeoutError
2020-10-05T15:41:47.766068+00:00 app[worker.1]: TimeoutError
2020-10-05T15:41:47.766068+00:00 app[worker.1]: 
2020-10-05T15:41:47.766069+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-10-05T15:41:47.766069+00:00 app[worker.1]: 
2020-10-05T15:41:47.766070+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-05T15:41:47.766070+00:00 app[worker.1]:   File "/app/bot/handlers/leech_handler.py", line 127, in progress_dl
2020-10-05T15:41:47.766070+00:00 app[worker.1]:     await message.edit(
2020-10-05T15:41:47.766072+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/client/types/messages_and_media/message.py", line 2507, in edit_text
2020-10-05T15:41:47.766072+00:00 app[worker.1]:     return await self._client.edit_message_text(
2020-10-05T15:41:47.766073+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/client/methods/messages/edit_message_text.py", line 78, in edit_message_text
2020-10-05T15:41:47.766074+00:00 app[worker.1]:     r = await self.send(
2020-10-05T15:41:47.766074+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/client/client.py", line 1424, in send
2020-10-05T15:41:47.766074+00:00 app[worker.1]:     r = await self.session.send(data, retries, timeout, self.sleep_threshold)
2020-10-05T15:41:47.766075+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
2020-10-05T15:41:47.766075+00:00 app[worker.1]:     return await self.send(data, retries - 1, timeout)
2020-10-05T15:41:47.766075+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
2020-10-05T15:41:47.766076+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2020-10-05T15:41:47.766076+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 399, in _send
2020-10-05T15:41:47.766077+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2020-10-05T15:41:47.766077+00:00 app[worker.1]:   File "/app/venv/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 79, in raise_it
2020-10-05T15:41:47.766078+00:00 app[worker.1]:     raise getattr(
2020-10-05T15:41:47.766078+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified (caused by "messages.EditMessage")

**Comment by azamaulanaaa** [comment]
@talkaal can I have the tracker list?

**Comment by talkaal** [comment]
Sure there's a GitHub page updating list for bit client and aria2 
Separate


**Trackers list**



http://1337.abcvg.info:80/announce,http://178.175.143.27:80/announce,http://5rt.tace.ru:60889/announce,http://78.30.254.12:2710/announce,http://91.217.91.21:3218/announce,http://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,http://[2001:470:1:189:0:1:2:3]:6969/announce,http://[2a04:ac00:1:3dd8::1:2710]:2710/announce,http://aaa.army:8866/announce,http://atrack.pow7.com:80/announce,http://bobbialbano.com:6969/announce,http://bt.3kb.xyz:80/announce,http://bt.pusacg.org:8080/announce,http://derpyradio.net:6969/announce,http://explodie.org:6969/announce,http://grifon.info:80/announce,http://h4.trakx.nibba.trade:80/announce,http://jsb.by:8000/announce,http://novaopcj.icu:10325/announce,http://ns349743.ip-91-121-106.eu:80/announce,http://open.acgnxtracker.com:80/announce,http://open.touki.ru:80/announce.php,http://opentracker.i2p.rocks:6969/announce,http://opentracker.xyz:80/announce,http://pow7.com:80/announce,http://publictracker.ch:6969/announce,http://retracker.hotplug.ru:2710/announce,http://retracker.sevstar.net:2710/announce,http://rt.tace.ru:80/announce,http://secure.pow7.com:80/announce,http://share.camoe.cn:8080/announce,http://t.acg.rip:6699/announce,http://t.nyaatracker.com:80/announce,http://t.overflow.biz:6969/announce,http://t1.pow7.com:80/announce,http://t2.pow7.com:80/announce,http://thetracker.org:80/announce,http://torrentsmd.com:8080/announce,http://torrenttracker.nwc.acsalaska.net:6969/announce,http://tr.cili001.com:8070/announce,http://tracker.anonwebz.xyz:8080/announce,http://tracker.birkenwald.de:6969/announce,http://tracker.bittor.pw:1337/announce,http://tracker.bittorrent.am:80/announce,http://tracker.bt4g.com:2095/announce,http://tracker.bz:80/announce,http://tracker.dler.org:6969/announce,http://tracker.dutchtracking.nl:80/announce,http://tracker.files.fm:6969/announce,http://tracker.gbitt.info:80/announce,http://tracker.ipv6tracker.ru:80/announce,http://tracker.kamigami.org:2710/announce,http://tracker.kuroy.me:5944/announce,http://tracker.lelux.fi:80/announce,http://tracker.moeking.me:6969/announce,http://tracker.noobsubs.net:80/announce,http://tracker.opentrackr.org:1337/announce,http://tracker.skyts.net:6969/announce,http://tracker.sloppyta.co:80/announce,http://tracker.trackerfix.com:80/announce,http://tracker.ygsub.com:6969/announce,http://tracker.zum.bi:6969/announce,http://tracker1.itzmx.com:8080/announce,http://tracker2.dler.org:80/announce,http://tracker2.itzmx.com:6961/announce,http://tracker3.itzmx.com:6961/announce,http://tracker4.itzmx.com:2710/announce,http://trun.tom.ru:80/announce,http://vpn.flying-datacenter.de:6969/announce,http://vps02.net.orel.ru:80/announce,http://www.wareztorrent.com:80/announce,https://1337.abcvg.info:443/announce,https://2.tracker.eu.org:443/announce,https://3.tracker.eu.org:443/announce,https://aaa.army:8866/announce,https://open.kickasstracker.com:443/announce,https://opentracker.acgnx.se:443/announce,https://tracker.bt-hash.com:443/announce,https://tracker.cyber-hub.net:443/announce,https://tracker.gbitt.info:443/announce,https://tracker.hama3.net:443/announce,https://tracker.imgoingto.icu:443/announce,https://tracker.lelux.fi:443/announce,https://tracker.nanoha.org:443/announce,https://tracker.nitrix.me:443/announce,https://tracker.parrotsec.org:443/announce,https://tracker.sloppyta.co:443/announce,https://tracker.tamersunion.org:443/announce,https://tracker6.lelux.fi:443/announce,https://trakx.herokuapp.com:443/announce,https://w.wwwww.wtf:443/announce,https://www.wareztorrent.com:443/announce,udp://104.238.198.186:8000/announce,udp://107.150.14.110:6969/announce,udp://109.121.134.121:1337/announce,udp://114.55.113.60:6969/announce,udp://128.199.70.66:5944/announce,udp://151.80.120.114:2710/announce,udp://168.235.67.63:6969/announce,udp://178.33.73.26:2710/announce,udp://182.176.139.129:6969/announce,udp://185.5.97.139:8089/announce,udp://185.83.215.123:6969/announce,udp://185.86.149.205:1337/announce,udp://188.165.253.109:1337/announce,udp://191.101.229.236:1337/announce,udp://194.106.216.222:80/announce,udp://195.123.209.37:1337/announce,udp://195.123.209.40:80/announce,udp://208.67.16.113:8000/announce,udp://212.1.226.176:2710/announce,udp://212.47.227.58:6969/announce,udp://213.163.67.56:1337/announce,udp://37.19.5.155:2710/announce,udp://3rt.tace.ru:60889/announce,udp://46.4.109.148:6969/announce,udp://47.ip-51-68-199.eu:6969/announce,udp://5.79.249.77:6969/announce,udp://5.79.83.193:6969/announce,udp://51.254.244.161:6969/announce,udp://52.58.128.163:6969/announce,udp://61626c.net:6969/announce,udp://62.138.0.158:6969/announce,udp://62.212.85.66:2710/announce,udp://74.82.52.209:6969/announce,udp://78.30.254.12:2710/announce,udp://85.17.19.180:80/announce,udp://89.234.156.205:80/announce,udp://9.rarbg.com:2710/announce,udp://9.rarbg.me:2710/announce,udp://9.rarbg.me:2780/announce,udp://9.rarbg.to:2710/announce,udp://9.rarbg.to:2730/announce,udp://91.216.110.52:451/announce,udp://91.218.230.81:6969/announce,udp://94.23.183.33:6969/announce,udp://95.211.168.204:2710/announce,udp://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,udp://[2001:470:1:189:0:1:2:3]:6969/announce,udp://[2a03:7220:8083:cd00::1]:451/announce,udp://[2a04:ac00:1:3dd8::1:2710]:2710/announce,udp://[2a04:c44:e00:32e0:4cf:6aff:fe00:aa1]:6969/announce,udp://aaa.army:8866/announce,udp://adm.category5.tv:6969/announce,udp://admin.videoenpoche.info:6969/announce,udp://adminion.n-blade.ru:6969/announce,udp://anidex.moe:6969/announce,udp://api.bitumconference.ru:6969/announce,udp://aruacfilmes.com.br:6969/announce,udp://asger.xyz:6969/announce,udp://bclearning.top:6969/announce,udp://benouworldtrip.fr:6969/announce,udp://bioquantum.co.za:6969/announce,udp://bitsparadise.info:6969/announce,udp://blokas.io:6969/announce,udp://bms-hosxp.com:6969/announce,udp://bt.firebit.org:2710/announce,udp://bt1.archive.org:6969/announce,udp://bt2.54new.com:8080/announce,udp://bt2.archive.org:6969/announce,udp://bubu.mapfactor.com:6969/announce,udp://camera.lei001.com:6969/announce,udp://cdn-1.gamecoast.org:6969/announce,udp://cdn-2.gamecoast.org:6969/announce,udp://chanchan.uchuu.co.uk:6969/announce,udp://chihaya.toss.li:9696/announce,udp://code2chicken.nl:6969/announce,udp://concen.org:6969/announce,udp://cutiegirl.ru:6969/announce,udp://daveking.com:6969/announce,udp://denis.stalker.upeer.me:6969/announce,udp://discord.heihachi.pw:6969/announce,udp://dpiui.reedlan.com:6969/announce,udp://drumkitx.com:6969/announce,udp://eddie4.nl:6969/announce,udp://edu.uifr.ru:6969/announce,udp://engplus.ru:6969/announce,udp://exodus.desync.com:6969/announce,udp://fe.dealclub.de:6969/announce,udp://forever-tracker.zooki.xyz:6969/announce,udp://free-tracker.zooki.xyz:6969/announce,udp://git.vulnix.sh:6969/announce,udp://inferno.demonoid.is:3391/announce,udp://inferno.demonoid.pw:3418/announce,udp://ipv4.tracker.harry.lu:80/announce,udp://ipv6.tracker.zerobytes.xyz:16661/announce,udp://jsb.by:8000/announce,udp://kanal-4.de:6969/announce,udp://koli.services:6969/announce,udp://line-net.ru:6969/announce,udp://ln.mtahost.co:6969/announce,udp://mail.realliferpg.de:6969/announce,udp://mgtracker.org:2710/announce,udp://movies.zsw.ca:6969/announce,udp://mts.tvbit.co:6969/announce,udp://nagios.tks.sumy.ua:80/announce,udp://ns-1.x-fins.com:6969/announce,udp://ns389251.ovh.net:6969/announce,udp://open.demonii.com:1337/announce,udp://open.lolicon.eu:7777/announce,udp://open.stealth.si:80/announce,udp://opentor.org:2710/announce,udp://opentracker.i2p.rocks:6969/announce,udp://public-tracker.zooki.xyz:6969/announce,udp://public.popcorn-tracker.org:6969/announce,udp://public.publictracker.xyz:6969/announce,udp://publictracker.xyz:6969/announce,udp://retracker.akado-ural.ru:80/announce,udp://retracker.hotplug.ru:2710/announce,udp://retracker.lanta-net.ru:2710/announce,udp://retracker.local.msn-net.ru:6969/announce,udp://retracker.netbynet.ru:2710/announce,udp://retracker.nts.su:2710/announce,udp://retracker.sevstar.net:2710/announce,udp://rutorrent.frontline-mod.com:6969/announce,udp://sd-161673.dedibox.fr:6969/announce,udp://shadowshq.eddie4.nl:6969/announce,udp://shadowshq.yi.org:6969/announce,udp://storage.groupees.com:6969/announce,udp://t1.leech.ie:1337/announce,udp://t2.leech.ie:1337/announce,udp://t3.leech.ie:1337/announce,udp://teamspeak.value-wolf.org:6969/announce,udp://thetracker.org:80/announce,udp://torrent.tdjs.tech:6969/announce,udp://tr.bangumi.moe:6969/announce,udp://tr.cili001.com:8070/announce,udp://tracker-udp.gbitt.info:80/announce,udp://tracker-v6.zooki.xyz:6969/announce,udp://tracker.0x.tf:6969/announce,udp://tracker.aletorrenty.pl:2710/announce,udp://tracker.altrosky.nl:6969/announce,udp://tracker.army:6969/announce,udp://tracker.beeimg.com:6969/announce,udp://tracker.birkenwald.de:6969/announce,udp://tracker.bittor.pw:1337/announce,udp://tracker.blacksparrowmedia.net:6969/announce,udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://tracker.dler.org:6969/announce,udp://tracker.ds.is:6969/announce,udp://tracker.dyne.org:6969/announce,udp://tracker.e-utp.net:6969/announce,udp://tracker.eddie4.nl:6969/announce,udp://tracker.ex.ua:80/announce,udp://tracker.filemail.com:6969/announce,udp://tracker.flashtorrents.org:6969/announce,udp://tracker.fortu.io:6969/announce,udp://tracker.grepler.com:6969/announce,udp://tracker.halfchub.club:6969/announce,udp://tracker.internetwarriors.net:1337/announce,udp://tracker.kali.org:6969/announce,udp://tracker.kamigami.org:2710/announce,udp://tracker.kuroy.me:5944/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://tracker.lelux.fi:6969/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.open-internet.nl:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://tracker.piratepublic.com:1337/announce,udp://tracker.publictracker.xyz:6969/announce,udp://tracker.shkinev.me:6969/announce,udp://tracker.skynetcloud.site:6969/announce,udp://tracker.skyts.net:6969/announce,udp://tracker.swateam.org.uk:2710/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tvunderground.org.ru:3218/announce,udp://tracker.uw0.xyz:6969/announce,udp://tracker.v6speed.org:6969/announce,udp://tracker.vulnix.sh:6969/announce,udp://tracker.yoshi210.com:6969/announce,udp://tracker.zemoj.com:6969/announce,udp://tracker.zerobytes.xyz:1337/announce,udp://tracker.zum.bi:6969/announce,udp://tracker0.ufibox.com:6969/announce,udp://tracker1.itzmx.com:8080/announce,udp://tracker2.christianbro.pw:6969/announce,udp://tracker2.dler.org:80/announce,udp://tracker2.indowebster.com:6969/announce,udp://tracker2.itzmx.com:6961/announce,udp://tracker3.itzmx.com:6961/announce,udp://tracker4.itzmx.com:2710/announce,udp://tracker6.dler.org:2710/announce,udp://tsundere.pw:6969/announce,udp://u.wwwww.wtf:1/announce,udp://ultra.zt.ua:6969/announce,udp://us-tracker.publictracker.xyz:6969/announce,udp://valakas.rollo.dnsabr.com:2710/announce,udp://vibe.community:6969/announce,udp://wassermann.online:6969/announce,udp://www.midea123.z-media.com.cn:6969/announce,udp://www.torrent.eu.org:451/announce,udp://zephir.monocul.us:6969/announce,udp://zer0day.ch:1337/announce,udp://zer0day.to:1337/announce

**Comment by alamia442** [comment]
# Tracker
bash <(curl -fsSL git.io/tracker.sh)

**Comment by azamaulanaaa** [comment]
@talkaal I did with your tracker and with benchmark torrent https://webtorrent.io/torrents/big-buck-bunny.torrent and it was fine. Then I did with your torrent, and it always fail at the middle of downloading with no error from aria2 idk why.

**Comment by talkaal** [comment]
Thank you for testing it.

A small feature request is requested on the closed issue #8
